server: 
  port: 8090
  # application.properties
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource: #마이바티스
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://petdoc.cdwhtnc4pcjb.ap-northeast-2.rds.amazonaws.com/petdoc?characterEncoding=UTF-8
    username: root
    password: root1234

  devtools: #자동실행
    livereload:
      enabled: true
      
  servlet:  #multipart
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
      
mybatis:
  type-aliases-package: com.multicampus.pet.vo #mybatis에서 패키지 생략 할 수 있도록 설정
  mapper-locations: mapper/*Mapper.xml #쿼리문 경로 지정x 
 

